#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

BRIDGE_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
if [[ "$ENV_FILE" == ".env" ]]; then
  ENV_FILE="$BRIDGE_ROOT/.env"
fi

banner "Telegram ↔ Mattermost Bridge"

stage "Создать Telegram-бота"
say "BotFather создаст отдельного технического бота для моста."
open_url "https://t.me/BotFather"
step "Откройте чат с @BotFather и выполните /newbot."
step "Задайте отображаемое имя и username, оканчивающийся на bot."
step "Скопируйте HTTP API token из ответа BotFather."
ask_secret TG_BOT_TOKEN "Вставьте TG_BOT_TOKEN:"
if [[ ! "$TG_BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]]; then
  warn "Токен Telegram имеет неожиданный формат. Проверьте его и запустите мастер снова."
  exit 1
fi
write_env TG_BOT_TOKEN "$TG_BOT_TOKEN"

stage "Подключить Telegram-группу"
say "Бот должен видеть обычные сообщения группы, а не только команды."
step "В @BotFather выполните /setprivacy, выберите бота и нажмите Disable."
step "Если бот уже был в группе, удалите его и добавьте заново."
step "Добавьте бота в чат с контрагентом и отправьте в этот чат тестовое сообщение."
pause "Нажмите Enter после отправки тестового сообщения."
if command -v python3 >/dev/null 2>&1; then
  note "Запрашиваю у Telegram список чатов из накопленных updates…"
  TG_CHAT_LIST=$(TG_SETUP_TOKEN="$TG_BOT_TOKEN" python3 - <<'PY' || true
import json
import os
import urllib.request

token = os.environ["TG_SETUP_TOKEN"]
with urllib.request.urlopen(
    f"https://api.telegram.org/bot{token}/getUpdates", timeout=15
) as response:
    payload = json.load(response)

chats = {}
for update in payload.get("result", []):
    message = update.get("message") or update.get("edited_message")
    if not message:
        continue
    chat = message.get("chat", {})
    chat_id = chat.get("id")
    if chat_id is None:
        continue
    label = chat.get("title") or chat.get("username") or chat.get("first_name") or "без названия"
    chats[str(chat_id)] = label

for chat_id, label in chats.items():
    print(f"{chat_id}  {label}")
PY
  )
  if [[ -n "$TG_CHAT_LIST" ]]; then
    say "Найденные чаты (ID и название):"
    while IFS= read -r line; do note "  $line"; done <<< "$TG_CHAT_LIST"
  else
    warn "Чаты не найдены. Проверьте, что бот добавлен и после этого получено новое сообщение."
  fi
else
  warn "python3 не найден — TG_CHAT_ID придётся получить через getUpdates вручную."
fi
ask TG_CHAT_ID "Введите числовой TG_CHAT_ID нужной группы:"
if [[ ! "$TG_CHAT_ID" =~ ^-?[0-9]+$ ]]; then
  warn "TG_CHAT_ID должен быть целым числом."
  exit 1
fi
write_env TG_CHAT_ID "$TG_CHAT_ID"

stage "Создать Mattermost-бота и выбрать канал"
say "Для моста нужен отдельный bot account только в выделенном приватном канале."
ask MM_URL "Введите базовый HTTPS URL Mattermost (например, https://mattermost.example.com):"
if [[ ! "$MM_URL" =~ ^https://[^[:space:]]+$ ]]; then
  warn "MM_URL должен быть полным HTTPS URL."
  exit 1
fi
open_url "$MM_URL"
step "В Mattermost откройте Product menu → Integrations → Bot Accounts."
step "Создайте bot account, сохраните access token и добавьте бота в нужную команду."
step "Создайте или выберите приватный канал для контрагента и добавьте туда бота."
ask_secret MM_BOT_TOKEN "Вставьте MM_BOT_TOKEN:"
if [[ -z "$MM_BOT_TOKEN" ]]; then
  warn "MM_BOT_TOKEN не может быть пустым."
  exit 1
fi
if command -v python3 >/dev/null 2>&1; then
  note "Запрашиваю Mattermost-каналы, доступные новому боту…"
  MM_CHANNEL_LIST=$(MM_SETUP_URL="$MM_URL" MM_SETUP_TOKEN="$MM_BOT_TOKEN" python3 - <<'PY' || true
import json
import os
import urllib.request

base = os.environ["MM_SETUP_URL"].rstrip("/")
headers = {"Authorization": f"Bearer {os.environ['MM_SETUP_TOKEN']}"}

def get(path):
    request = urllib.request.Request(base + path, headers=headers)
    with urllib.request.urlopen(request, timeout=15) as response:
        return json.load(response)

teams = get("/api/v4/users/me/teams")
for team in teams:
    channels = get(f"/api/v4/users/me/teams/{team['id']}/channels")
    for channel in channels:
        print(
            f"{channel['id']}  {team.get('display_name', team.get('name', ''))} / "
            f"{channel.get('display_name', channel.get('name', ''))}"
        )
PY
  )
  if [[ -n "$MM_CHANNEL_LIST" ]]; then
    say "Каналы, доступные боту (ID, команда и канал):"
    while IFS= read -r line; do note "  $line"; done <<< "$MM_CHANNEL_LIST"
  else
    warn "Каналы не найдены. Проверьте токен и членство бота, затем повторите мастер."
  fi
fi
ask MM_CHANNEL_ID "Введите MM_CHANNEL_ID выделенного канала:"
if [[ ! "$MM_CHANNEL_ID" =~ ^[a-z0-9]{20,32}$ ]]; then
  warn "ID канала Mattermost имеет неожиданный формат. Проверьте значение."
  exit 1
fi
write_env MM_URL "$MM_URL"
write_env MM_BOT_TOKEN "$MM_BOT_TOKEN"
write_env MM_CHANNEL_ID "$MM_CHANNEL_ID"
write_env DB_PATH "/data/bridge.db"
write_env HTTP_BIND "0.0.0.0:8080"
write_env LOG_LEVEL "INFO"
write_env MAX_ATTACHMENT_BYTES "26214400"
chmod 600 "$ENV_FILE"

finish
say "Конфигурация готова. Не публикуйте $ENV_FILE и не отправляйте токены в чат."
say "Сообщите исполнителю только о завершении мастера — содержимое .env он перенесёт защищённо."
